### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [princessbeepbop/prj-rev-bwfs-dasmoto#5]
https://github.com/princessbeepbop/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L14-L17

Your CSS is also very poorly indented. Make sure you come back to this and clean up the indentation a bit so you're consistent throughout the file.

You should not be repeating these shared styles in every single CSS rule. Move them into their own CSS rule so you only need to change them in one place:

```css
h2 {
    font-size: 32px;
    font-weight: bold;
    color: White;
}
```

Notice I didn't include the font. SInce all of the elements on the page have the same font, you can just put that into its CSS rule with the universal selector `*`.
```css
* {
    font-family: Helvetica;
}
```
